
import * as upgoerfive from "../upgoerfive";

var quotes = [
  "All those moments will be lost in time… like tears in rain.",
  "Bond. James Bond.",
  "A boy's best friend is his mother.",
  "But then I realised maybe that's what hell is: the entire rest of eternity spent in f_____g Bruges. And I really really hoped I wouldn't die.",
  "Daddy! My Daddy!",
  "Did you think I'd be too stupid to know what a eugoogly is?",
  "Do I look like I give a damn?",
  "Do I look like someone who cares what God thinks?",
  "ET phone home.",
  "Enough is enough! I have had it with these motherf_____g snakes on this motherf_____g plane!",
  "Ever since I can remember I always wanted to be a gangster. To me that was better than being president of the United States. To be a gangster was to own the world.",
  "Everybody runs, Fletch.",
  "Fasten your seat belts, it's going to be a bumpy night!",
  "Frankly, my dear, I don't give a damn!",
  "Get busy living, or get busy dying.",
  "Go ahead, make my day.",
  "Here's another nice mess you've gotten me into!",
  "Here's looking at you, kid.",
  "He's not the Messiah. He's a very naughty boy!",
  "Hey, don't knock masturbation. It's sex with someone I love.",
  "Hope. It is the only thing stronger than fear. A little hope is effective. A lot of hope is dangerous. A spark is fine, as long as it's contained.",
  "How do you like them apples?",
  "I am Groot",
  "I am Spartacus.",
  "I ate his liver with some fava beans and a nice chianti.",
  "I coulda had class. I coulda been a contender. I coulda been somebody.",
  "I drink your milkshake!",
  "I love lamp.",
  "I never had any friends later on like the ones I had when I was 12. Jesus, does anyone?",
  "I see dead people.",
  "I want to be alone.",
  "I want to play a game...",
  "I wish I knew how to quit you.",
  "If you build it, he will come.",
  "If you are looking for ransom, I can tell you I don't have money. But what I do have are a very particular set of skills, skills I have acquired over a very long career. Skills that make me a nightmare for people like you. ",
  "If you figure a way to live without serving a master, any master, then let the rest of us know, will you? For you'd be the first person in the history of the world.",
  "I'll be back.",
  "I'll have what she's having.",
  "I'm also just a girl standing in front of a boy asking him to love her.",
  "I'm as mad as hell, and I'm not gonna to take this anymore!",
  "I'm gonna make him an offer he can't refuse.",
  "I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking. And I plan on finding out what that is.",
  "I'm ready for my close-up.",
  "I'm very sorry for your loss. Your mother was a terribly attractive woman.",
  "In case I don't see ya, good afternoon, good evening, and good night!",
  "In Switzerland they had brotherly love – and 500 years of democracy and peace, and what did that produce? The cuckoo clock.",
  "Infamy, infamy, they've all got it in for me!",
  "It was beauty killed the beast.",
  "It's a mess, ain't it, sheriff?",
  "If it ain't, it'll do till the mess gets here.",
  "It's not murder, it's ketchup.",
  "Just keep swimming.",
  "Let's go to the Winchester, have a pint and wait for this to all blow over",
  "Life is a box of chocolates, Forrest. You never know what you're gonna get.",
  "Life is only on earth, and not for long.",
  "Louis, I think this is the beginning of a beautiful friendship.",
  "Man who catch fly with chopstick accomplish anything.",
  "May the Force be with you.",
  "My name is Maximus Decimus Meridius, commander of the Armies of the North, General of the Felix Legions and loyal servant to the true emperor, Marcus Aurelius, father to a murdered son, husband to a murdered wife. And I will have my vengeance, in this life or the next.",
  "Nobody puts Baby in a corner.",
  "Nobody's perfect.",
  "Norway has trolls, so more power lines are needed. That's just the way it is.",
  "Now you're looking for the secret, but you won't find it, because of course you're not really looking. You don't really want to know. You want to be fooled.",
  "Oh my gosh, look at that fluffy unicorn! He's so fluffy, I'm gonna die!",
  "Oh, Jerry, don't let's ask for the moon. We have the stars.",
  "Rosebud.",
  "Say hello to my little friend.",
  "Say what you like about the Nazis... they had style.",
  "That was the most fun I've ever had without laughing.",
  "That's the way it crumbles, cookie-wise.",
  "The cold never bothered me anyway.",
  "To call you stupid would be an insult to stupid people!",
  "To infinity… and beyond.",
  "Toto, I've a feeling we're not in Kansas anymore.",
  "We want the finest wines available to humanity. And we want them here, and we want them now!",
  "Well, what if there is no tomorrow? There wasn't one today.",
  "What did you expect, an exploding pen?",
  "Why so serious?",
  "You can't fool me. There ain't no Sanity Clause!",
  "You go Glen Coco!",
  "You had me at hello.",
  "You know how to whistle, don't you, Steve? You just put your lips together and… blow.",
  "You smell like pine needles and you have a face like sunshine.",
  "You talkin' to me?",
  "You're gonna need a bigger boat.",
  "You're not an asshole, Mark. You're just trying so hard to be."
]

quotes.forEach(q => {
  var s = q.replace(/[^a-z0-9\s]/gi,'');
  var badValues = upgoerfive.replace(s);
  console.log(`${s} => [ ${badValues}]`);
});
